import type { EucastBreakpointRecord } from "../types";
import { EUCAST_2026_METADATA } from "./notes";

const ENTEROBACTERALES_SOURCE = "EUCAST v16.0 2026, Enterobacterales";

export const EUCAST_2026_ENTEROBACTERALES_BREAKPOINTS: EucastBreakpointRecord[] = [
  // Penicillins
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMP",
    method: "mic",
    susceptibleMaxMgL: 8,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ampicillin iv`,
    notes:
      "Candidate record. EUCAST row: Ampicillin iv. No I category because S and R breakpoints are equal.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMP",
    method: "disk",
    susceptibleMinMm: 14,
    resistantLessThanMm: 14,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ampicillin iv`,
    notes: "Candidate record. EUCAST row: Ampicillin iv. Disk note A applies.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMC",
    method: "mic",
    susceptibleMaxMgL: 8,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Amoxicillin-clavulanic acid iv`,
    notes:
      "Candidate record for IV/systemic row only. Oral and UTI-specific rows differ and are not modelled here. Clavulanic acid fixed at 2 mg/L.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMC",
    method: "disk",
    susceptibleMinMm: 19,
    resistantLessThanMm: 19,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Amoxicillin-clavulanic acid iv`,
    notes:
      "Candidate record for IV/systemic row only. Disk content 20-10 µg. ATU 19-20 mm requires later ATU support.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "TZP",
    method: "mic",
    susceptibleMaxMgL: 8,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Piperacillin-tazobactam`,
    notes:
      "Candidate record. Tazobactam fixed at 4 mg/L. MIC ATU 16 mg/L requires later ATU support.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "TZP",
    method: "disk",
    susceptibleMinMm: 20,
    resistantLessThanMm: 20,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Piperacillin-tazobactam`,
    notes: "Candidate record. Disk content 30-6 µg. ATU 19 mm requires later ATU support.",
  },

  // Cephalosporins
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "FEP",
    method: "mic",
    susceptibleMaxMgL: 1,
    resistantGreaterThanMgL: 4,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefepime`,
    notes: "Candidate record. EUCAST I is susceptible, increased exposure.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "FEP",
    method: "disk",
    susceptibleMinMm: 27,
    resistantLessThanMm: 24,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefepime`,
    notes: "Candidate record. Disk content 30 µg.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CTX",
    method: "mic",
    susceptibleMaxMgL: 1,
    resistantGreaterThanMgL: 2,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefotaxime, indications other than meningitis`,
    notes: "Candidate record. Meningitis-specific row excluded.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CTX",
    method: "disk",
    susceptibleMinMm: 20,
    resistantLessThanMm: 17,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefotaxime, indications other than meningitis`,
    notes: "Candidate record. Disk content 5 µg. Meningitis-specific row excluded.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CXM",
    method: "mic",
    susceptibleMaxMgL: 0.001,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefuroxime iv (E. coli, Klebsiella spp. except K. aerogenes, Raoultella spp., P. mirabilis)`,
    notes:
      "Transcribed from EUCAST v16.0 cefuroxime iv row. Includes organism-scope caveat from source row.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CXM",
    method: "disk",
    susceptibleMinMm: 50,
    resistantLessThanMm: 19,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Cefuroxime iv (E. coli, Klebsiella spp. except K. aerogenes, Raoultella spp., P. mirabilis)`,
    notes:
      "Transcribed from EUCAST v16.0 cefuroxime iv row (disk content 30 µg). Includes organism-scope caveat from source row.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CAZ",
    method: "mic",
    susceptibleMaxMgL: 1,
    resistantGreaterThanMgL: 4,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ceftazidime`,
    notes: "Candidate record.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CAZ",
    method: "disk",
    susceptibleMinMm: 22,
    resistantLessThanMm: 19,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ceftazidime`,
    notes: "Candidate record. Disk content 10 µg.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CRO",
    method: "mic",
    susceptibleMaxMgL: 1,
    resistantGreaterThanMgL: 2,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ceftriaxone, indications other than meningitis`,
    notes: "Candidate record. Meningitis-specific row excluded.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CRO",
    method: "disk",
    susceptibleMinMm: 27,
    resistantLessThanMm: 24,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ceftriaxone, indications other than meningitis`,
    notes: "Candidate record. Disk content 30 µg. Meningitis-specific row excluded.",
  },

  // Carbapenems
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "ETP",
    method: "mic",
    susceptibleMaxMgL: 0.5,
    resistantGreaterThanMgL: 0.5,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ertapenem`,
    notes: "Candidate record. No I category because S and R breakpoints are equal.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "ETP",
    method: "disk",
    susceptibleMinMm: 23,
    resistantLessThanMm: 23,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ertapenem`,
    notes: "Candidate record. Disk content 10 µg.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "IPM",
    method: "mic",
    susceptibleMaxMgL: 2,
    resistantGreaterThanMgL: 4,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Imipenem, Enterobacterales except Morganellaceae`,
    notes:
      "Candidate record. Requires subgroup handling before activation because Morganellaceae have separate breakpoints.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "IPM",
    method: "disk",
    susceptibleMinMm: 22,
    resistantLessThanMm: 19,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Imipenem, Enterobacterales except Morganellaceae`,
    notes: "Candidate record. Disk content 10 µg. Requires subgroup handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "MEM",
    method: "mic",
    susceptibleMaxMgL: 2,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Meropenem, indications other than meningitis`,
    notes: "Candidate record. Meningitis-specific row excluded.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "MEM",
    method: "disk",
    susceptibleMinMm: 22,
    resistantLessThanMm: 16,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Meropenem, indications other than meningitis`,
    notes: "Candidate record. Disk content 10 µg. Meningitis-specific row excluded.",
  },

  // Monobactams
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "ATM",
    method: "mic",
    susceptibleMaxMgL: 1,
    resistantGreaterThanMgL: 4,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Aztreonam`,
    notes:
      "Candidate record. Verify project antibiotic code is ATM; do not activate if dictionary uses another code.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "ATM",
    method: "disk",
    susceptibleMinMm: 26,
    resistantLessThanMm: 21,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Aztreonam`,
    notes: "Candidate record. Disk content 30 µg. Verify project antibiotic code is ATM.",
  },

  // Fluoroquinolones
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CIP",
    method: "mic",
    susceptibleMaxMgL: 0.25,
    resistantGreaterThanMgL: 0.5,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ciprofloxacin, indications other than meningitis`,
    notes:
      "Candidate record. Salmonella-specific and meningitis-specific rows excluded. MIC ATU 0.5 mg/L requires later ATU support.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "CIP",
    method: "disk",
    susceptibleMinMm: 25,
    resistantLessThanMm: 22,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Ciprofloxacin, indications other than meningitis`,
    notes: "Candidate record. Disk content 5 µg. ATU 22-24 mm requires later ATU support.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "LVX",
    method: "mic",
    susceptibleMaxMgL: 0.5,
    resistantGreaterThanMgL: 1,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Levofloxacin`,
    notes: "Candidate record.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "LVX",
    method: "disk",
    susceptibleMinMm: 23,
    resistantLessThanMm: 19,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Levofloxacin`,
    notes: "Candidate record. Disk content 5 µg.",
  },

  // Aminoglycosides
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMK",
    method: "mic",
    susceptibleMaxMgL: 8,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Amikacin, infections originating from the urinary tract`,
    notes:
      "Candidate record for infections originating from the urinary tract. Systemic bracketed breakpoint excluded. Requires specimen/indication handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "AMK",
    method: "disk",
    susceptibleMinMm: 18,
    resistantLessThanMm: 18,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Amikacin, infections originating from the urinary tract`,
    notes:
      "Candidate record. Disk content 30 µg. Requires specimen/indication handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "GEN",
    method: "mic",
    susceptibleMaxMgL: 2,
    resistantGreaterThanMgL: 2,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Gentamicin, infections originating from the urinary tract`,
    notes:
      "Candidate record for infections originating from the urinary tract. Systemic bracketed breakpoint excluded. Requires specimen/indication handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "GEN",
    method: "disk",
    susceptibleMinMm: 17,
    resistantLessThanMm: 17,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Gentamicin, infections originating from the urinary tract`,
    notes:
      "Candidate record. Disk content 10 µg. Requires specimen/indication handling before activation.",
  },

  // UTI and miscellaneous agents
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "NIT",
    method: "mic",
    susceptibleMaxMgL: 64,
    resistantGreaterThanMgL: 64,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Nitrofurantoin, uncomplicated UTI only, E. coli`,
    notes:
      "Candidate record. Applies to uncomplicated UTI only and E. coli only. Requires specimen and species handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "NIT",
    method: "disk",
    susceptibleMinMm: 11,
    resistantLessThanMm: 11,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Nitrofurantoin, uncomplicated UTI only, E. coli`,
    notes:
      "Candidate record. Disk content 100 µg. Applies to uncomplicated UTI only and E. coli only.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "FOS",
    method: "mic",
    susceptibleMaxMgL: 8,
    resistantGreaterThanMgL: 8,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "needs_validation",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Fosfomycin oral, uncomplicated UTI only, E. coli`,
    notes:
      "Candidate record. Applies to uncomplicated UTI only and E. coli only. Agar dilution with glucose-6-phosphate requirements apply.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "FOS",
    method: "disk",
    susceptibleMinMm: 24,
    resistantLessThanMm: 24,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "needs_validation",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Fosfomycin oral, uncomplicated UTI only, E. coli`,
    notes:
      "Candidate record. Disk content 200 µg with glucose-6-phosphate. Specific reading instructions apply: ignore isolated colonies and read outer zone edge.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "SXT",
    method: "mic",
    susceptibleMaxMgL: 0.5,
    resistantGreaterThanMgL: 0.5,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Trimethoprim-sulfamethoxazole, Enterobacterales except Serratia spp.`,
    notes:
      "Candidate record. Breakpoints expressed as trimethoprim concentration. Serratia spp. have separate breakpoints and require subgroup handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "SXT",
    method: "disk",
    susceptibleMinMm: 15,
    resistantLessThanMm: 15,
    interpretationCategories: ["S", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Trimethoprim-sulfamethoxazole, Enterobacterales except Serratia spp.`,
    notes:
      "Candidate record. Disk content 1.25-23.75 µg. Serratia spp. have separate breakpoints and require subgroup handling before activation.",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "TGC",
    method: "mic",
    susceptibleMaxMgL: 0.5,
    resistantGreaterThanMgL: 0.5,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Tigecycline (E. coli and K. oxytoca)`,
    notes:
      "Transcribed from EUCAST v16.0 tigecycline row. Species scope caveat applies (E. coli and K. oxytoca).",
  },
  {
    ...EUCAST_2026_METADATA,
    organismGroup: "enterobacterales",
    antibioticCode: "TGC",
    method: "disk",
    susceptibleMinMm: 18,
    resistantLessThanMm: 18,
    interpretationCategories: ["S", "I", "R", "ND"],
    breakpointStatus: "active",
    sourceTableRef: `${ENTEROBACTERALES_SOURCE}, Tigecycline (E. coli and K. oxytoca)`,
    notes:
      "Transcribed from EUCAST v16.0 tigecycline row (disk content 15 µg). Species scope caveat applies (E. coli and K. oxytoca).",
  },
];
