/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IpcRouteImport } from './routes/ipc'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmsRouteImport } from './routes/ams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSoundsRouteImport } from './routes/settings.sounds'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReceiversRouteImport } from './routes/admin.receivers'
import { Route as AdminConfigRouteImport } from './routes/admin.config'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IpcRoute = IpcRouteImport.update({
  id: '/ipc',
  path: '/ipc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmsRoute = AmsRouteImport.update({
  id: '/ams',
  path: '/ams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSoundsRoute = SettingsSoundsRouteImport.update({
  id: '/settings/sounds',
  path: '/settings/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReceiversRoute = AdminReceiversRouteImport.update({
  id: '/admin/receivers',
  path: '/admin/receivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/ipc': typeof IpcRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/receivers': typeof AdminReceiversRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/sounds': typeof SettingsSoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/ipc': typeof IpcRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/receivers': typeof AdminReceiversRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/sounds': typeof SettingsSoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/ipc': typeof IpcRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/receivers': typeof AdminReceiversRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/sounds': typeof SettingsSoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ams'
    | '/analytics'
    | '/audit'
    | '/ipc'
    | '/login'
    | '/signup'
    | '/admin/config'
    | '/admin/receivers'
    | '/admin/users'
    | '/settings/sounds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ams'
    | '/analytics'
    | '/audit'
    | '/ipc'
    | '/login'
    | '/signup'
    | '/admin/config'
    | '/admin/receivers'
    | '/admin/users'
    | '/settings/sounds'
  id:
    | '__root__'
    | '/'
    | '/ams'
    | '/analytics'
    | '/audit'
    | '/ipc'
    | '/login'
    | '/signup'
    | '/admin/config'
    | '/admin/receivers'
    | '/admin/users'
    | '/settings/sounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmsRoute: typeof AmsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  IpcRoute: typeof IpcRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminReceiversRoute: typeof AdminReceiversRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SettingsSoundsRoute: typeof SettingsSoundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipc': {
      id: '/ipc'
      path: '/ipc'
      fullPath: '/ipc'
      preLoaderRoute: typeof IpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ams': {
      id: '/ams'
      path: '/ams'
      fullPath: '/ams'
      preLoaderRoute: typeof AmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sounds': {
      id: '/settings/sounds'
      path: '/settings/sounds'
      fullPath: '/settings/sounds'
      preLoaderRoute: typeof SettingsSoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/receivers': {
      id: '/admin/receivers'
      path: '/admin/receivers'
      fullPath: '/admin/receivers'
      preLoaderRoute: typeof AdminReceiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmsRoute: AmsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  IpcRoute: IpcRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminReceiversRoute: AdminReceiversRoute,
  AdminUsersRoute: AdminUsersRoute,
  SettingsSoundsRoute: SettingsSoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
