// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const processEnv = typeof process === "undefined" ? undefined : process.env;
const SUPABASE_DISABLED_MESSAGE =
  "Supabase is not configured for this deployment. Running in local/no-auth mode.";

function createNoopQueryBuilder(): any {
  let proxy: any;
  const handler: ProxyHandler<(...args: unknown[]) => unknown> = {
    get(_target, prop) {
      if (prop === "then") {
        return (resolve: (value: unknown) => void) =>
          resolve({
            data: null,
            error: new Error(SUPABASE_DISABLED_MESSAGE),
            count: 0,
            status: 503,
            statusText: "Supabase disabled",
          });
      }
      if (prop === "catch") {
        return () => proxy;
      }
      if (prop === "finally") {
        return (cb: () => void) => {
          cb();
          return proxy;
        };
      }
      return proxy;
    },
    apply() {
      return proxy;
    },
  };
  proxy = new Proxy((() => undefined) as (...args: unknown[]) => unknown, handler);
  return proxy;
}

function createDisabledSupabaseClient() {
  const query = createNoopQueryBuilder();
  return {
    auth: {
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => undefined } },
      }),
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: new Error(SUPABASE_DISABLED_MESSAGE) }),
      signOut: async () => ({ error: null }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error(SUPABASE_DISABLED_MESSAGE),
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: new Error(SUPABASE_DISABLED_MESSAGE),
      }),
      resetPasswordForEmail: async () => ({ data: null, error: new Error(SUPABASE_DISABLED_MESSAGE) }),
      updateUser: async () => ({ data: null, error: new Error(SUPABASE_DISABLED_MESSAGE) }),
      setSession: async () => ({ data: null, error: new Error(SUPABASE_DISABLED_MESSAGE) }),
    },
    from: () => query,
    rpc: () => query,
    channel: () => query,
    removeChannel: async () => ({ error: null }),
  };
}

export function isSupabaseConfigured(): boolean {
  const supabaseUrl =
    import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL || processEnv?.SUPABASE_URL;
  const supabasePublishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_ANON_KEY ||
    processEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ||
    processEnv?.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    processEnv?.SUPABASE_PUBLISHABLE_KEY;
  return Boolean(supabaseUrl && supabasePublishableKey);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL || processEnv?.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_ANON_KEY ||
    processEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ||
    processEnv?.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    processEnv?.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createDisabledSupabaseClient() as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
